### PR TITLE
adjusted structure finally

### PR DESCRIPTION
**Pull request by anderja2000**
merging into main updated strcuture

### CODE REVIEW

**Review by kyliewilson799 — APPROVED** [review]
looks good.

**Comment by kyliewilson799** [comment]
good.

**Review by kyliewilson799 — APPROVED** [review]

**Comment by kyliewilson799** [comment]
good.

**Comment by anderja2000** [comment]
chekced

**Review by kyliewilson799 — APPROVED** [review]
good.

**Comment by kyliewilson799** [comment]
good.

**Review by anderja2000 — COMMENTED** [review]
all good

**Pull request merged**
